# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CgcSAQE6AggNEgoIAUADSAFQHmgB
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
  device:
    nodeInfoBroadcastSecs: 10800
  display:
    screenOnSecs: 600
  lora:
    hopLimit: 3
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 30
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    gpsMode: ENABLED
    gpsUpdateInterval: 120
    positionBroadcastSecs: 900
    positionBroadcastSmartEnabled: true
    positionFlags: 811
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    serialEnabled: true
module_config:
  ambientLighting:
    blue: 200
    current: 10
    green: 44
    red: 219
  cannedMessage:
    enabled: true
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh
    username: meshdev
  telemetry:
    deviceUpdateInterval: 2147483647
owner: Meshtastic 2cc8
owner_short: 2cc8

